#
#   Author: Rohith
#   Date: 2015-06-15 16:30:54 +0100 (Mon, 15 Jun 2015)
#
#  vim:ts=2:sw=2:et
#
---

default_coreos: &COREOS_BOX_DEFAULT
  box: "coreos-beta"
  url: "http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"
  cloudinit: 'config/cloudinit.coreos.virtualbox.erb'
  gui: false

default_coreos_virtualbox: &COREOS_CORE_BOX_DEFAULT
  resources:
    cpus: 1
    memory: 2048
    biosbootmenu: disabled
  <<: *COREOS_BOX_DEFAULT

default_coreos_virtualbox: &COREOS_STORE_BOX_DEFAULT
  resources:
    cpus: 1
    memory: 1024
    biosbootmenu: disabled
  <<: *COREOS_BOX_DEFAULT

boxes:  
  store101.sbx.example.com:
    virtualbox:
      <<: *COREOS_STORE_BOX_DEFAULT
      ip: 10.250.1.51
      disks:
      - name: docker
        size: 12040
      - name: ceph
        size: 8192
    metadata:
       ceph_monitor: true
       ceph_osd: true
  store102.sbx.example.com:
    virtualbox:
      <<: *COREOS_STORE_BOX_DEFAULT
      ip: 10.250.1.52
      disks:
      - name: docker
        size: 12040
      - name: ceph
        size: 8192
    metadata:
      ceph_monitor: true
      ceph_osd: true

  store103.sbx.example.com:
    virtualbox:
      <<: *COREOS_STORE_BOX_DEFAULT
      ip: 10.250.1.53
      disks:
      - name: docker
        size: 12040
      - name: ceph
        size: 8192
    metadata:
      ceph_monitor: true
      ceph_osd: true
  store104.sbx.example.com:
    virtualbox:
      <<: *COREOS_STORE_BOX_DEFAULT
      ip: 10.250.1.54
      disks:
      - name: docker
        size: 12040
      - name: ceph
        size: 8192
    metadata:
      ceph_monitor: true
      ceph_osd: true
  bastion101.sbx.example.com:
    virtualbox:
      <<: *COREOS_CORE_BOX_DEFAULT
      ip: 10.250.1.61
    metadata:
      kubernetes: true
      role: bastion
  core101.sbx.example.com:
    virtualbox:
      <<: *COREOS_CORE_BOX_DEFAULT
      ip: 10.250.1.203
      disks:
      - name: docker
        size: 12040
    metadata:
      kubernetes: true
      etcd_master: true
      role: minion
      id: 1
  core102.sbx.example.com:
    virtualbox:
      <<: *COREOS_CORE_BOX_DEFAULT
      ip: 10.250.1.204
      disks:
      - name: docker
        size: 12040
    metadata:
      kubernetes: true
      etcd_master: true
      role: minion
      id: 2
  core103.sbx.example.com:
    virtualbox:
      <<: *COREOS_CORE_BOX_DEFAULT
      ip: 10.250.1.205
      disks:
      - name: docker
        size: 12040
    metadata:
      kubernetes: true
      etcd_master: true
      role: minion
      id: 3
